apiVersion: v2
name: openshift-gitops
description: Installs and patches the Red Hat Openshift Gitops Operator
version: 1.0.48
icon: https://github.com/tjungbauer/helm-charts/raw/gh-pages/images/argo-icon-color.png
home: https://github.com/tjungbauer/helm-charts/tree/main/charts/openshift-gitops
maintainers:
  - name: tjungbauer
    email: tjungbau@redhat.com
    url: https://blog.stderr.at/
sources:
  - https://github.com/tjungbauer/helm-charts
  - https://charts.stderr.at/
  - https://github.com/tjungbauer/openshift-clusterconfig-gitops
dependencies:
  - name: tpl
    version: ~1.0.0
    repository: https://charts.stderr.at/
keywords:
  - gitops
  - management
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/signKey: |
    fingerprint: B677CB52F8358FA091044E375D24D6846DBA8F8A
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/B677CB52F8358FA091044E375D24D6846DBA8F8A
  artifacthub.io/changes: |
    - kind: fixed
      description: Signing Chart
    - kind: added
      description: Added customer Health Checks to Argo CD Patch-yaml
    - kind: fixed
      description: changed Argo CD CRD to v1beta1
    - kind: fixed
      description: typo in health check
    - kind: added
      description: cleaning up chart, added new README and tried to make more options configurable.
    - kind: added
      description: allowing configuration of syncwave for Argo CD object.
    - kind: fixed
      description: updated ArgoCD resource to v1beta1
    - kind: added
      description: added ClusterRolebinding to enable cluster-admin permissions for Argo CD in case it is enabled
    - kind: fixed
      description: fixing some default Values
    - kind: added
      description: added tpl chart
    - kind: added
      description: switching some snippets to use global tpl
    - kind: added
      description: it is now possible to define a global AppProject
    - kind: added
      description: it is now possible to define the name of a ConfigMap with the list of custom CAs, that will be used inside the Repo Pod
